### ISSUE TITLE
USER STORY - Start a countdown

### ISSUE THREAD

**Issue by Owen-Gibbs** [Owen-Gibbs/countdown-app#1]
As a **USER** 
I can **ENTER A DATE & TIME INTO AN INPUT BOX TO START A COUNTDOWN** 
So that **I CAN CREATE A COUNTDOWN TIMER** 

# Acceptance Criteria

- Input box with date & time placeholder
- Start countdown button
- Countdown Clock

# Tasks

- [x] Develop a input for the date & time
- [x] Develop a button to start countdown
- [ ] Style the input field & button using CSS
- [x] Write javaScript for countdown functionality
