### ISSUE TITLE
USER STORY - Reset countdown

### ISSUE THREAD

**Issue by Owen-Gibbs** [Owen-Gibbs/countdown-app#2]
As a **USER** 
I can **RESET THE COUNTDOWN WHEN IT'S FINISHED** 
So that **I CAN BEGIN A NEW COUNTDOWN** 

# Acceptance Criteria

- Must have a reset button when the countdown finishes
- Reset button will rest the countdown
- Reset button will clear the previous countdown

# Tasks

- [x] Develop a reset button in html
- [x] Style the reset button with CSS
- [x] Write the javaScript for the reset button functionality
